export const GET_COUNTRIES= "GET_COUNTRIES";
export const GET_STATES = 'GET_STATES'
export const GET_CITIES = 'GET_CITIES'
export const CLEAN_STATE_FORM = 'CLEAN_STATE_FORM'
export const POST_FORM_REGISTER = 'POST_FORM_REGISTER'
export const GET_PETS_FILTER = 'GET_PETS_FILTER'
export const GET_PETS = 'GET_PETS'

